FROM ubuntu:22.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
build-essential \
cmake \
git \
tcl8.6 \
libreadline-dev \
zlib1g-dev \
&& rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY . /app

RUN git clone https://github.com/berkeley-abc/abc.git /tmp/abc && \
cd /tmp/abc && \
make -j$(nproc) && \
cp abc /usr/local/bin/

RUN mkdir -p build && \
cmake -S . -B ./build && \
cmake —build ./build -j$(nproc)

COPY runTests.sh /runTests.sh
RUN chmod +x /runTests.sh

CMD ["bash", "/runTests.sh"]